TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 2
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: giant_pandas/giant_pandas/
  NUM_FRAMES: 8
  SAMPLING_RATE: 18
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  # STEPS: [0, 16, 22]
  STEPS: [0, 22, 28]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
  # WEIGHT_DECAY: 0.05
  # OPTIMIZING_METHOD: adamw
MODEL:
  MODEL_NAME: crossvit_base_224
  NUM_CLASSES: 5
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 2
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
  CHECKPOINT_FILE_PATH: 'output/test/timesformer_crossvit_15e_44/checkpoints/checkpoint_epoch_00015.pyth'
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
# RNG_SEED: 28
# OUTPUT_DIR: ./output/timesformer_40_crossvit_18_224_sgd_24e_rpe_test/
